bower.json
src/vaadin-rich-text-editor.html

Closes #1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/13)

Add vaadin-license-checker

---

src/vaadin-rich-text-editor.html
test/basic.html

Fixes #3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/15)

Implement htmlValue getter for the editor content

---

src/vaadin-rich-text-editor.html
test/basic.html

Connects to #18
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/19)

Change value type to String

---

src/vaadin-rich-text-editor.html
test/accessibility.html
test/test-suites.js

connects to #8 
Tested on:
- NVDA (works)
- JAWS (works)
- VoiceOver (couldn't find a way to get text formatting announcements to work. Other than that, all good)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/21)

Improve screen reader support

---

src/vaadin-rich-text-editor.html
test/accessibility.html

connects to #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/25)

Improve keyboard navigation

---

src/vaadin-rich-text-editor.html

Fixes #9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/38)

Update API docs: add description and state attributes [skip ci]

---

src/vaadin-rich-text-editor-content-styles.html
src/vaadin-rich-text-editor-toolbar-styles.html
src/vaadin-rich-text-editor.html

Fixes #33
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/42)

Make content fill the full editor

---

src/vaadin-rich-text-editor.html
test/accessibility.html

Fixes #35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/44)

Use titles instead of aria-labels in the toolbar buttons

---

test/basic.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/48)

Fix version number test to allow alpha and beta

---

demo/rich-text-editor-basic-demos.html

Fixes #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/82)

Remove readonly demo [skip ci]

---

src/vaadin-rich-text-editor.html
test/basic.html

Fixes #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/79)

Add state attribute for toolbar buttons

---

src/vaadin-rich-text-editor.html
test/basic.html

Fixes #77
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/84)

Set default value to be empty string

---

gulpfile.js
src/vaadin-rich-text-editor-icons.html
src/vaadin-rich-text-editor-styles.html
src/vaadin-rich-text-editor-toolbar-styles.html
src/vaadin-rich-text-editor.html
test/basic.html
theme/lumo/vaadin-rich-text-editor-styles.html
theme/material/vaadin-rich-text-editor-styles.html

Fixes #59
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/83)

Rename stylable parts, use state attribute in core and theme styles

---

demo/demos.json
demo/index.html
demo/rich-text-editor-styling-demos.html

Fixes #76
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/85)

Add custom styling demo [skip ci]

---

src/vaadin-rich-text-editor.html
test/accessibility.html
wct.conf.js

Fixes #90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/93)

Fix disappearing cursor and Shift+Tab issue in Firefox

---

README.md

Fixes #102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/104)

Document workaround for using with webpack [skip ci]

---

src/vaadin-rich-text-editor.html

Fixes #61
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-rich-text-editor/110)

Add unique parts for toolbar-groups

---

src/vaadin-rich-text-editor-content-styles.html
src/vaadin-rich-text-editor.html
test/.eslintrc.json
test/basic.html

Fix RTL default alignment

---

src/vaadin-rich-text-editor.html
test/basic.html

Cherry-pick of #141 to `1.2` branch for 14.3

fix: update value in read-only state on API call (#141)

---

bower.json
package-lock-p3.json

Update `vaadin-text-field` dependency to `2.10.0`

chore: update vaadin-text-field to 2.10.0
